<?php

/**
 * Implements hook_menu().
 */

function hologram_menu(){
    $items['hologram/upload'] = array(
        'page callback' => 'hologram_upload',
        'access arguments' => array('administer media'),
    );

    return $items;
}

function hologram_upload(){
    header('Content-type:application/json;charset=utf-8');
    $request = file_get_contents('php://input');
    $upload_path = variable_get('file_public_path', conf_path() . '/files');
    $file = json_decode($request);
    if($file){
        $data = base64_decode(preg_replace('#^data:image/\w+;base64,#i', '', $file->preview));
        try{
            $file_data = file_save_data($data, 'public://' . $file->name, FILE_EXISTS_REPLACE);
            $uploaded_file = array('id'=> $file_data->fid, 'name' => $file->name, 'size' => $file->size, 'uploaded_date'=> (new DateTime())->getTimestamp());
            echo json_encode($uploaded_file, JSON_UNESCAPED_UNICODE);
        }catch(Exception $e){
            $result = array('message'=>'Upload Failed!', 'error' => $e);
            echo json_encode($result);
        }
    }
    exit();
}

/**
* Implements hook_field_widget_info().
*/
function hologram_field_widget_info(){
    return array(
        'hologram_image' => array(
            'label' => t('Hologram'),
            'field types' => array('image'),
        )
    );
}

/**
* Implements hook_field_widget_form().
*
*/
function hologram_field_widget_form(&$form, &$form_state, $field, $instance, $langcode, $items, $delta, $element) {
    $upload_path = '/' . variable_get('file_public_path', conf_path() . '/files/');
    drupal_add_css(drupal_get_path('module', 'hologram') . '/hologram/dist/css/hologram.css');
    drupal_add_js(drupal_get_path('module', 'hologram') . '/hologram/dist/bundle.js');
    drupal_add_js(drupal_get_path('module', 'hologram') . '/js/widget.js');
    drupal_add_js(array('Hologram' => array('uploadUrl' => $upload_path)), array('type' => 'setting'));

    $element['value'] = array(
      'image'=> array(
        '#type' => 'managed_file',
      ),

      'image_json' => array(
        '#type' => 'hidden',
        '#default_value' => isset($items['image_json']) ? $items['image_json'] : ''
      ),
      'hologram' => array(
        '#title' => t('Images'),
        '#type' => 'markup',
        '#markup' => '<div class="hologram-wrapper"><label>Images</label><div class="hologram-area"></div></div>',
      ),
    );

    //$element['#process'][] = 'hologram_field_widget_process';

    return $element;
}

function hologram_field_widget_process($element, &$form_state, $form){
  $item = $element['value'];
}


function hologram_field_is_empty($item, $field) {
  return empty($item['value']) && (string) $item['value'] !== '0';
}

?>
