<?php

/**
 * Implements hook_menu().
 */

function hologram_menu(){
    $items['hologram/upload'] = array(
        'page callback' => 'hologram_upload',
        'access arguments' => array('administer media'),
    );

    return $items;
}

function hologram_upload(){
    header('Content-type:application/json;charset=utf-8');
    $request = file_get_contents('php://input');
    $file = json_decode($request);
    if($file){
        $data = base64_decode(preg_replace('#^data:image/\w+;base64,#i', '', $file->preview));
        try{
            file_put_contents('sites/default/files/' . $file->name, $data);
            $uploaded_file = array('name' => $file->name, 'size' => $file->size, 'uploaded_date'=> (new DateTime())->getTimestamp());
            echo json_encode($uploaded_file, JSON_UNESCAPED_UNICODE);
        }catch(Exception $e){
            $result = array('message'=>'Upload Failed!', 'error' => $e);
            echo json_encode($result);
        }
    }
    exit();
}

/**
* Implements hook_field_widget_info().
*/
function hologram_field_widget_info(){
    return array(
        'hologram_image' => array(
            'label' => t('Hologram'),
            'field types' => array('image'),
        )
    );
}

/**
* Implements hook_field_widget_form().
*
*/
function hologram_field_widget_form(&$form, &$form_state, $field, $instance, $langcode, $items, $delta, $element) {
    drupal_add_css(drupal_get_path('module', 'hologram') . '/hologram/dist/css/hologram.css');
    drupal_add_js(drupal_get_path('module', 'hologram') . '/hologram/dist/bundle.js');
    drupal_add_js(drupal_get_path('module', 'hologram') . '/js/widget.js');

    $element['value'] = array(
        'field' => array(
            '#type' => 'hidden',
            '#default_value' => isset($items[$delta]) ? $items[$delta] : '',
        ),
        'hologram' => array(
            '#title' => t('Images'),
            '#type' => 'markup',
            '#markup' => '<div class="hologram-wrapper"><label>Images</label><div class="hologram-area"></div></div>',
        ),
    );

    return $element;
}



?>
